### ISSUE TITLE
Clear normalisation/regularisation strategy for data

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#231]
Currently it is unclear what is exactly done / should be done from raw data to `final` processed data.
I.e. things like normalisation of units, inference of values like SE from SD, ...
How to distinguish the raw data from the processed data.

This will solve
#210 duplicate outputs
#215 clean and clear inference of parameters

And is related to 
#105 calculating pharmacokinetics data from timecourses

**Comment by janekg89** [comment]
For outputs and timecourses and interventions have keyword `normed` and outputs have the keyword `calculated` which indicate if the respective data is normalized (unit normalization with respective values; and inference of error measures like cv, se, sd, ...)
