### ISSUE TITLE
Dimensionless unit must be normalized

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#263]
The dimensionless units are not normalized. E.g. in sex characteristica of individuals some entries have "-", some have "". All dimensionless units should be "-", so it is clear that the unit dimensionless was assigned on purpose, compared to just not providing a unit.

**Comment by janekg89** [comment]
TODO: make check that `""` is not allowed in json.study. Either no unit field (interpreted as dimensionless) or use `"-"`.
