### ISSUE TITLE
Simplify user creation, registration and authentication

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#338]
This should just work as simple as possible between backend and frontend.
- [x] create new user
- [x] email confirmation
- [x] change password

Make the authentication process working consistently via the frontend.
(duplicate of #178)

**Comment by janekg89** [comment]
this should work now. Has to be tested in production

**Comment by matthiaskoenig** [comment]
Just tried this in production and get the following error:
```
TypeError: "cannot use 'in' operator to search for 'username' in '<html>

<head><t...'"
    user_warnings Registration.vue:49
    VueJS 3
    Ks Registration.vue:1
    VueJS 7
    o es6.promise.js:75
    P es6.promise.js:92
    c _microtask.js:18
vue.runtime.esm.js:1888
    VueJS 10
    o es6.promise.js:75
    P es6.promise.js:92
    c _microtask.js:18
```

**Comment by matthiaskoenig** [comment]
testing via separate issue.
