### ISSUE TITLE
Warning during Normalization

### ISSUE THREAD

**Issue by janekg89** [matthiaskoenig/pkdb#436]
should we investigate this warning?
```
/code/pkdb_app/normalization.py:72: RuntimeWarning: invalid value encountered in true_divide
backend_1        |   cv = np.true_divide(np.multiply(se, np.sqrt(count)), mean)
```

**Comment by janekg89** [comment]
if mean == 0 coefficient of variance cannot be calculated. This happens quite often for timecourse data at t==0. Maybe this warning should be added as a validation error.

**Comment by matthiaskoenig** [comment]
Closing this for now.
