### ISSUE TITLE
Validate that TSV does not have any "Unnamed" or empty columns

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#441]
Example `caffeine/Blanchard1982/Tab2`
When there is text next to the table unnamed and empty columns are generated. This should be forbidden.
- Validate no column header starts with "Unnamed"
- Validate no column is completely empty, i.e. only NA values

Example at commit https://github.com/matthiaskoenig/pkdb_data/commit/63aab75711eb5c3fcefed2f28e1f4dd6f05db16b

**Comment by janekg89** [comment]
both is already part of validation. 
complete empty columns are drop
