### ISSUE TITLE
Bug in auc_inf calculation if timcourse increases on last datapoints

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#450]
Some strange timecourses can result in incorrectly calculated auc_inf.
E.g. `acetaminophen/Langford2016` calculation of `auc_inf`. Due to last timepoint being higher than the one before very high auc_inf is calculated for 1g.

**Comment by YannickDuport** [comment]
In midazolam/Vanakoski1996 this leads to a negativ AUCinf (AUC_inf for p110 = -1.03e-4)
