### ISSUE TITLE
Support indexing in google datasets

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#524]
Individual datasets should be accessible on google dataset search.
https://developers.google.com/search/docs/data-types/dataset
Addition markup is required which allows for simple reuse of datasets

> We can understand structured data in Web pages about datasets, using either schema.org Dataset markup, or equivalent structures represented in W3C's Data Catalog Vocabulary (DCAT) format. We also are exploring experimental support for structured data based on W3C CSVW, and expect to evolve and adapt our approach as best practices for dataset description emerge. For more information about our approach to dataset discovery, see Making it easier to discover datasets.

**Comment by janekg89** [comment]
We might also consider being visible on https://data.mendeley.com/.

**Comment by matthiaskoenig** [comment]
No priority. Closing this for now. Reopen if becomes relevant.
