### ISSUE TITLE
Improve upload speed of upload_nodes

### ISSUE THREAD

**Issue by janekg89** [matthiaskoenig/pkdb#543]

**Comment by matthiaskoenig** [comment]
@janekg89 Provide more specific descriptions for issue. 
Currently, it takes very long to upload the `info_nodes` in the database. This is mainly due to individual upload of every node. Via batch upload the upload speed can be improved.

**Comment by janekg89** [comment]
The upload speed of the info nodes improved by ~2.5. This is still not a true bulk create (multiple database calls but only 1 rest request). The loop is now on the server-side. 
```
(pkdb_data) janek@dell-desktop:~/Dev/pkdb_data$ upload_nodes
> INFO upload info nodes: http://0.0.0.0:8000
> INFO - 31.41 [s] : Upload info_nodes (old)
> INFO - 78.13 [s] : Upload info_nodes
```
