### ISSUE TITLE
Validate that recoveries are < 2.0 if dimensionless or < 200 if in percent

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#558]
Measurement types in which `percent` and `dimensionless` can be used as units are often encoded incorrectly. Add validation rules to get warnings/errors for that:
- if in percent: warning if > 100 and < 200; error if > 200
- if in dimensionless: warning if > 1.0 and < 2.0; error if > 2.0

Same for other measurement types which have units percent/dimensionless

**Comment by janekg89** [comment]
I have not implemented a mechanism to return warnings from rest api. Warnings are currently only possible on validation in pkdata.
