### ISSUE TITLE
Check that no empty lines in data tables

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#581]
The excel sheets should not contain any empty lines in the data. Give warning if empty lines in data.
Having empty lines will make it much more difficult to work with the excel sheets or the TSV.
Basically the excel spread sheets should be a block of 2D data, nothing else. The only exception right now are comments via `#` because we don't have support for the comments yet.

**Comment by janekg89** [comment]
I added a warning. However, do not think that empty rows were possible in the first place. We already validate that the content of the first column has to be the study name.
