### ISSUE TITLE
Provide direct study link (persistent url)

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/pkdb#624]
- [ ] Create URL to access data from single study (populate store)
- [ ] Update the pkdb_data links in `upload_study` for direct access

**Comment by matthiaskoenig** [comment]
@janekg89 This is a priority. I have to access often the data for a single study in the curation process. The direct links do not work right now, i.e. the following link after SUCCESSFUL
```
INFO - 17.11 [s] : Upload study
INFO --------------------------------------------------------------------------------
INFO http://0.0.0.0:8000/api/v1/_studies/PKDB00300/
INFO UPLOAD SUCCESSFUL (http://0.0.0.0:8081/studies/PKDB00300)

```

**Comment by janekg89** [comment]
http://0.0.0.0:8081/data/PKDB00300

**Comment by janekg89** [comment]
http://0.0.0.0:8081/data/PKDB00300/
