### ISSUE TITLE
Empty download file for interventions

### ISSUE THREAD

**Issue by Gotsmy** [matthiaskoenig/pkdb#683]
Great Project! I have one issue though:

I tried to download a whole study (as shown in pkdb_api.ipynb) with this url: https://pk-db.com/api/v1/filter/?studies__name=Abernethy1985&download=true, but the interventions.csv file is empty.

But when I request the interventions via the uuid (https://pk-db.com/api/v1/interventions/?uuid=6f4bba72-9ce2-46f0-be7a-789e0a17b289&format=json) i get a non-empty file back (that also lists Abernethy1985 as study).

**Comment by matthiaskoenig** [comment]
@Gotsmy Thanks for the report. We will fix the issue within the next few days. 
@janekg89 Make this a priority.

**Comment by janekg89** [comment]
Whit new deployment bug should be fixed.

**Comment by matthiaskoenig** [comment]
Changes are deployed on the server. The upload of the data takes another ~30 minutes.
@Gotsmy feel free to test with another already uploaded study for now.

Best Matthias

**Comment by Gotsmy** [comment]
Works like a charm!

Thank you & best,
Mathias
