### ISSUE TITLE
Data Empty?

### ISSUE THREAD

**Issue by danieldjewell** [matthiaskoenig/pkdb#728]
Hi, 

The repository at https://github.com/matthiaskoenig/pkdb_data (as referenced in the docs) is no longer available and the API returns zero results (from https://github.com/matthiaskoenig/pkdb/blob/develop/docs/pkdb_api.ipynb) 

The output of https://pk-db.com/api/v1/statistics/?format=json is:

```json
{
  "version": "0.9.6",
  "study_count": 0,
  "reference_count": 0,
  "group_count": 0,
  "individual_count": 0,
  "intervention_count": 0,
  "output_count": 0,
  "output_calculated_count": 0,
  "timecourse_count": 0,
  "scatter_count": 0
}

```

What's up with that?

**Comment by matthiaskoenig** [comment]
There was an issue in some automatic deploy script. Could you use the develop server
https://alpha.pk-db.com
while we fix the issue. Sorry for the inconvenience.

**Comment by danieldjewell** [comment]
No worries, thanks for the link to the alpha server. 

What about access to the source data? Has that been removed for some reason?

Vielen dank!

**Comment by matthiaskoenig** [comment]
Access to the source data? You should be able to download via the download link or the API. Could you provide some more information on what you try to do then we can provide support?

**Comment by matthiaskoenig** [comment]
Just fixed this. Sorry for the delay. Database is uploading and will be ready in the next hours.
Best Matthias
