### ISSUE TITLE
Mistakes in Patwardhan1980a

### ISSUE THREAD

**Issue by ReneGeci** [matthiaskoenig/pkdb#738]
Hello,

I believe there is something wrong with the timecourses from Patwardhan1980a. Especially timecourse 4468. The data points are a wild mix, as far as i can see they dont fit any of the figures I can see in the publication. The publication has 3 figures x 2 cpnditions, ie 6 timecourses, whereas PKDB shows 8 timecourses for the publication. And the time values for timecourse 4468 are also a wild mix ("[15.0, 5.0, 10.0, 30.0, 60.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, 24.0, 32.0, 48.0, 56.0]")...

**Comment by janekg89** [comment]
Hi Rene, thank you for helping with data quality. I skimmed over Patwardhan1980a (https://pubmed.ncbi.nlm.nih.gov/6106621/). Data from Tab1, Tab2, Fig1, Fig2 were curated:  Fig1 and Fig2 contain timecourses. Each contains 4 timecourses. Are we talking about the same publication? Greetings

**Comment by janekg89** [comment]
There was indeed a curation mistake in Patwardhan1980a. The time unit was wrong for some of the values. Now, this should be fixed. See: https://alpha.pk-db.com/data/PKDB00337?tab=timecourses

**Comment by ReneGeci** [comment]
@janekg89 , the timecourse seems more plausible now. thanks!

but indeed we did not talk about the same publication. the elsevier link did not work for me, and a not further to be named website promoting open access to scientific literature provided me with the wrong paper :D
