### ISSUE TITLE
Hovorka2002 has wrong concentration values

### ISSUE THREAD

**Issue by ReneGeci** [matthiaskoenig/pkdb#740]
hello,

the Hovorka2002 timecourse of glucose (216) has concentration (mean) values that are not consistent with the values in the referenced publication.

Fig 2 (top) shows glucose concentrations in the range between 5 and 16 mmol/l. Given a MW of 180 g/mol this should be a range of 0.9 to 2.88 g/l.
However, the given valuesare in the range between  0.05 and 0.15 g/l.
It seems that sth went wrong in the conversion of the values.

**Comment by matthiaskoenig** [comment]
Thanks for reporting the issue. The units were indeed incorrectly curated as mg/dl. This has now been fixed.
Best Matthias
