### ISSUE TITLE
difference pk-db.com and alpha.pk-db.com

### ISSUE THREAD

**Issue by ReneGeci** [matthiaskoenig/pkdb#743]
Hello,

it seems that the websites are not identical, the alpha website shows more studies. what is the difference between them?

**Comment by janekg89** [comment]
Hi Rene, alpha is our staging server used to test the website in a production-similar environment.

**Comment by ReneGeci** [comment]
thanks for the clarification! so that means both have PK data of equal curated quality, its just that they are uploaded first to the alpha server, correct?

**Comment by janekg89** [comment]
Yes. The workflow is as follows: Studies get curated and uploaded on alpha first. After getting checked by a second experienced curator, they get a proper unique identifier (https://bioregistry.io/registry/pkdb) and finally uploaded to PK-DB.

**Comment by ReneGeci** [comment]
That makes sense, thank a lot!
