### ISSUE TITLE
Wrong concentration values for Figure 3 Hecken1985 (Subject 5)

### ISSUE THREAD

**Issue by ReneGeci** [matthiaskoenig/pkdb#744]
I believe the timecourse concentration values for Subject 5 from Hecken1985 (taken from Figure 3) are wrong by a factor of 10.
PKDB for this subject says values are in the range 10-25 microgram/l
but it should be 100-250 microgram/l (which is also the range the other timecourses are in)

**Comment by janekg89** [comment]
Hi Rene, thank you. Just fixed the curation mistake and reuploaded to alpha, see https://alpha.pk-db.com/data/PKDB00336?tab=studies.
