### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by ReneGeci** [matthiaskoenig/pkdb#746]
there seems to be an issue with the websites being unavailable:

"NET::ERR_CERT_COMMON_NAME_INVALID"

**Comment by matthiaskoenig** [comment]
Sorry, the complete data center went into maintainance due to a cooling leakage. The site should be up latest on Friday, trying to spin up another server tomorrow.

**Comment by ReneGeci** [comment]
thanks a lot for the quick response! :)

**Comment by ReneGeci** [comment]
servers are up again
