### ISSUE TITLE
Bae 2014 has wrong timecourse values

### ISSUE THREAD

**Issue by ReneGeci** [matthiaskoenig/pkdb#747]
Something seems to be wrong with the timecourses for study "Bae2014".

The 2 PKDB timecourses for metropolol show values in the range 0.5 - 1.5 mg/l
But Figure3a in the corresponding publication has values in the range 0.2 - 0.5 mg/l

Same for the 2 timecourses for HMT.
The 2 PKDB timecourses show  values in the range 50  150 microg/l
But Figure 3b in the publication has values in the range 10- 100 microg/l

**Comment by matthiaskoenig** [comment]
Data was incorrectly digitized on a linear axis. Data has been redigitized and issue is fixed. Thanks for the report.
